"""
Local riddle bank — 150 curated riddles with single-word answers.
No API, no cost, instant response.
"""

RIDDLES = [
    ("I speak without a mouth and hear without ears. I have no body, but come alive with wind.", "echo"),
    ("The more you take, the more you leave behind.", "footsteps"),
    ("I have cities, but no houses live there. I have mountains, but no trees grow. I have water, but no fish swim. What am I?", "map"),
    ("What has hands but can't clap?", "clock"),
    ("I have a head and a tail, but no body.", "coin"),
    ("The more of this there is, the less you see.", "darkness"),
    ("I go up but never come down.", "age"),
    ("What can run but never walks, has a mouth but never talks?", "river"),
    ("I am not alive, but I grow. I don't have lungs, but I need air. What am I?", "fire"),
    ("I have keys but no locks. I have space but no room.", "keyboard"),
    ("What has one eye but can't see?", "needle"),
    ("I am always hungry and must always be fed. The finger I touch will soon turn red.", "fire"),
    ("What comes once in a minute, twice in a moment, but never in a thousand years?", "m"),
    ("I fly without wings. I cry without eyes.", "cloud"),
    ("You can catch me but cannot throw me.", "cold"),
    ("I have branches but no fruit, trunk, or leaves.", "bank"),
    ("What is full of holes but still holds water?", "sponge"),
    ("What gets wetter the more it dries?", "towel"),
    ("I'm tall when I'm young and short when I'm old.", "candle"),
    ("What has many teeth but can't bite?", "comb"),
    ("I have a neck but no head, and I wear a cap.", "bottle"),
    ("What invention lets you look through a wall?", "window"),
    ("What goes up and down without moving?", "staircase"),
    ("I am light as a feather, yet the strongest man can't hold me for more than five minutes.", "breath"),
    ("The more you feed me, the bigger I grow. What am I?", "fire"),
    ("What has a bottom at the top?", "leg"),
    ("What gets sharper the more you use it?", "brain"),
    ("I run but have no legs. I have a bed but never sleep.", "river"),
    ("What can be cracked, made, told, and played?", "joke"),
    ("I have a thumb and four fingers but I'm not a hand.", "glove"),
    ("What two things can you never eat for breakfast?", "lunch"),
    ("What word becomes shorter when you add two letters to it?", "short"),
    ("I have streets but no asphalt, cities but no buildings.", "atlas"),
    ("What is always coming but never arrives?", "tomorrow"),
    ("The more you take away, the bigger I become.", "hole"),
    ("What can you hold in your right hand but never in your left?", "left"),
    ("What goes through towns and over hills but never moves?", "road"),
    ("What has a ring but no finger?", "telephone"),
    ("What tastes better than it smells?", "tongue"),
    ("I have no life but I can die. What am I?", "battery"),
    ("I am an odd number. Take away a letter and I become even.", "seven"),
    ("What runs around the whole yard without moving?", "fence"),
    ("I can shout, whisper, and sing, but I have no voice box.", "wind"),
    ("What has a thousand needles but cannot sew?", "porcupine"),
    ("What is black when you buy it, red when you use it, and gray when you throw it away?", "charcoal"),
    ("I have four legs in the morning, two at noon, and three at night.", "human"),
    ("What can travel around the world while staying in a corner?", "stamp"),
    ("I am taken from a mine, shut in a wooden case, and used by almost everyone. What am I?", "pencil"),
    ("What belongs to you but is used more by others?", "name"),
    ("What question can you never answer yes to?", "asleep"),
    ("What is so fragile that saying its name breaks it?", "silence"),
    ("I have no wings but I can fly. I have no eyes but I can cry.", "cloud"),
    ("What building has the most stories?", "library"),
    ("I am bought by the yard and worn by the foot.", "carpet"),
    ("The man who makes it doesn't need it. The man who buys it doesn't want it. The man who uses it doesn't know.", "coffin"),
    ("I am always in front of you but cannot be seen.", "future"),
    ("What gets bigger the more you take away?", "hole"),
    ("I have lakes with no water, mountains with no stone, cities with no buildings.", "map"),
    ("What am I? The more you have of me, the less you see.", "fog"),
    ("I wave but have no hand. I dance but have no feet.", "flame"),
    ("What is yours but others use it more?", "name"),
    ("I have keys but no locks, I have a space but no room.", "piano"),
    ("What do you throw out when you want to use it and take in when you don't want it?", "anchor"),
    ("I go in hard, come out soft, and you blow me.", "gum"),
    ("The more it dries, the wetter it gets.", "towel"),
    ("What can run but not walk?", "water"),
    ("What is always on its way but never arrives?", "horizon"),
    ("I have a face but no eyes, hands but no arms.", "clock"),
    ("What is brown and sticky?", "stick"),
    ("I can be flipped but am not a pancake. I can be tossed but am not a salad.", "coin"),
    ("What kind of tree can you carry in your hand?", "palm"),
    ("What letter of the alphabet is an insect?", "b"),
    ("I shrink every time I work.", "eraser"),
    ("What do you fill with empty hands?", "gloves"),
    ("Remove my skin and I won't cry, but you will.", "onion"),
    ("I have no doors but I have keys. I have no rooms but I have space.", "keyboard"),
    ("What animal keeps the best time?", "watchdog"),
    ("What can you make that no one, not even you, can see?", "noise"),
    ("I have one head, one foot, and four legs.", "bed"),
    ("What has ears but cannot hear?", "cornfield"),
    ("What gets bigger the more you share it?", "happiness"),
    ("I go in wet and come out dry.", "pasta"),
    ("What has a spine but no bones?", "book"),
    ("I have cities, mountains, and oceans but no people live in me.", "globe"),
    ("What kind of coat can only be put on wet?", "paint"),
    ("I can be long or short. I can be grown or bought.", "hair"),
    ("What has a face, two hands, but no mouth?", "clock"),
    ("What is always hungry and always fed, and when you water it, it dies?", "fire"),
    ("What has four fingers and a thumb but is not alive?", "glove"),
    ("A word I know, six letters it contains, subtract just one, and twelve remains.", "dozens"),
    ("What jumps when it walks and sits when it stands?", "kangaroo"),
    ("I wear a crown but am not a king. I give light but am not the sun.", "lantern"),
    ("The person who makes me does not need me. The person who needs me cannot use me.", "coffin"),
    ("What begins with T, ends with T, and has T in it?", "teapot"),
    ("I can be good or bad, kind or wicked. I always reflect who you are. What am I?", "mirror"),
    ("What is the end of everything?", "g"),
    ("What is so delicate that saying its name breaks it?", "silence"),
    ("I cannot be burned in fire or drowned in water. What am I?", "ice"),
    ("What can you keep even after giving it to someone else?", "promise"),
    ("What goes up when rain comes down?", "umbrella"),
    ("What is the only question you can never say yes to?", "dead"),
    ("I am the beginning of the end, and the end of time. I am in the middle of the sea. What am I?", "e"),
    ("What runs but has no legs?", "nose"),
    ("I have cities but no trees. I have roads but no cars.", "map"),
    ("What word is spelled wrong in every dictionary?", "wrong"),
    ("I can be touched but not seen. I can be felt but not held.", "emotion"),
    ("What can fill a room but takes up no space?", "light"),
    ("What do you break before you use it?", "egg"),
    ("I am hard like stone, but I grow on your body.", "nail"),
    ("What has a bottom at its very top?", "leg"),
    ("What is full of holes but still holds water?", "net"),
    ("What has one eye but cannot see anything at all?", "hurricane"),
    ("What goes up and never comes down?", "smoke"),
    ("I have no heart but still pump blood. What am I?", "machine"),
    ("I sleep during the day and fly at night without feathers.", "bat"),
    ("What is orange and sounds like a parrot?", "carrot"),
    ("What is cut on a table but is never eaten?", "cards"),
    ("I am light as a feather, but even the world's strongest man couldn't hold me.", "breath"),
    ("What runs all around a backyard, yet never moves?", "fence"),
    ("What can point in every direction but can't reach the destination by itself?", "finger"),
    ("What can be seen in the middle of March and April that can't be seen at the beginning or end?", "r"),
    ("I wave without hands. I strike without arms. What am I?", "lightning"),
    ("What can fill a glass but weigh nothing?", "hole"),
    ("What five-letter word becomes shorter when you add two letters?", "shore"),
    ("I live in winter, die in summer, and grow with my roots upward.", "icicle"),
    ("I am taken from a mine and shut in a wooden case, from which I am never released.", "pencil"),
    ("What begins with an E but only has one letter in it?", "envelope"),
    ("What is as light as a feather but even the strongest person cannot hold for long?", "breath"),
    ("I run forever but never move a single inch.", "clock"),
    ("A box without hinges, key or lid, yet golden treasure inside is hid.", "egg"),
    ("What is always ahead of you but can never be reached?", "future"),
    ("What has no beginning, end, or middle?", "donut"),
    ("I go around in circles but always straight ahead.", "wheel"),
    ("What breaks without making a sound?", "wave"),
    ("I am not alive but I can grow. I don't have lungs but I need air to live.", "flame"),
    ("What kind of room has no doors or windows?", "mushroom"),
    ("What flies without wings and cries without eyes?", "wind"),
    ("What can be stolen, mistaken, or altered, yet never leaves you?", "identity"),
    ("I have arms but I can't carry anything.", "river"),
    ("What is always in bed but never sleeps?", "riverbed"),
    ("What comes down but never goes up?", "rain"),
    ("The one who makes it sells it. The one who buys it uses it never.", "tombstone"),
    ("What can you swallow that can also swallow you?", "water"),
    ("What loses its head in the morning and gets it back at night?", "pillow"),
    ("What can you hold without ever touching it?", "conversation"),
]
